apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oyejkcu8w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oyejkcu8w-nodejs 
  name: oyejkcu8w-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oyejkcu8w-nodejs 
